version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py

formats:
  - epub

python:
  install:
    - requirements: requirements/docs_requirements.txt
    - requirements: requirements/requirements.txt
